// <auto-generated />
using System;
using BudgetTrackerApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BudgetTrackerApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260206193308_RenamePea")]
    partial class RenamePea
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("BudgetTrackerApi.Data.CcCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("MacroCategory")
                        .HasColumnType("TEXT")
                        .HasColumnName("macro_category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("cc_categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MacroCategory = "Obligatoire",
                            Name = "Prêt"
                        },
                        new
                        {
                            Id = 2,
                            MacroCategory = "Obligatoire",
                            Name = "Courses"
                        },
                        new
                        {
                            Id = 3,
                            MacroCategory = "Obligatoire",
                            Name = "Travaux"
                        },
                        new
                        {
                            Id = 4,
                            MacroCategory = "Loisir",
                            Name = "Loisir"
                        },
                        new
                        {
                            Id = 5,
                            MacroCategory = "Loisir",
                            Name = "Vacances"
                        },
                        new
                        {
                            Id = 6,
                            MacroCategory = "Obligatoire",
                            Name = "Transport"
                        },
                        new
                        {
                            Id = 7,
                            MacroCategory = "Obligatoire",
                            Name = "Factures"
                        },
                        new
                        {
                            Id = 8,
                            MacroCategory = "Obligatoire",
                            Name = "Vêtements"
                        },
                        new
                        {
                            Id = 9,
                            MacroCategory = "Loisir",
                            Name = "Cadeaux"
                        },
                        new
                        {
                            Id = 10,
                            MacroCategory = "Obligatoire",
                            Name = "Santé"
                        },
                        new
                        {
                            Id = 11,
                            MacroCategory = "Obligatoire",
                            Name = "Autres"
                        },
                        new
                        {
                            Id = 12,
                            MacroCategory = "Obligatoire",
                            Name = "Maison/Equip."
                        },
                        new
                        {
                            Id = 13,
                            MacroCategory = "Neutre",
                            Name = "Neutre"
                        },
                        new
                        {
                            Id = 14,
                            MacroCategory = "Revenu",
                            Name = "Revenu"
                        });
                });

            modelBuilder.Entity("BudgetTrackerApi.Models.CcCategoryRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT")
                        .HasColumnName("comment");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_used");

                    b.Property<DateTime?>("LastAppliedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_applied_at");

                    b.Property<double?>("MaxAmount")
                        .HasColumnType("REAL")
                        .HasColumnName("max_amount");

                    b.Property<DateTime?>("MaxDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("max_date");

                    b.Property<double?>("MinAmount")
                        .HasColumnType("REAL")
                        .HasColumnName("min_amount");

                    b.Property<DateTime?>("MinDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("min_date");

                    b.Property<string>("Pattern")
                        .HasColumnType("TEXT")
                        .HasColumnName("pattern");

                    b.Property<int>("UsageCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usage_count");

                    b.HasKey("Id");

                    b.ToTable("cc_category_rules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Santé",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "VIR GENERATION",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 2,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "MAISON LEGUI",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 3,
                            Category = "Travaux",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Castorama",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 4,
                            Category = "Factures",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Sfr",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 5,
                            Category = "Ammeublement",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "edm",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 6,
                            Category = "Prêt",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Assu. Cnp Pret Habitat",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 7,
                            Category = "Santé",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Bio's Hair",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 8,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Auchan Le Mans",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 9,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Boulangerie",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 10,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Carrefour City Le Mans",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 11,
                            Category = "Factures",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "PRLV DIRECTION GENERALE DES FINA",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 12,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Carrefour Lemans",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 13,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Casino Shop",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 14,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Eleveurs Regionaux",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 15,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Fournil D'edison",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 16,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Grand*Frais",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 17,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Leclerc*Web",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 18,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Lidl",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 19,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Mgp*la Ruche",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 20,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Mie*Caline",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 21,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "U Express",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 22,
                            Category = "Factures",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Direct*Energie",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 23,
                            Category = "Factures",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "ENI Gas",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 24,
                            Category = "Factures",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Tres.  Le Mans Ville",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 25,
                            Category = "Transport",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Auchan Carburant",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 26,
                            Category = "Transport",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Dac Intermarche",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 27,
                            Category = "Transport",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "E.Leclerc Laval Cedex",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 28,
                            Category = "Transport",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Relais*Le*Mans*R",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 29,
                            Category = "Transport",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Stat Leclerc 24/24",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 30,
                            Category = "Transport",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Station U 72",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 31,
                            Category = "Factures",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Cabriole",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 32,
                            Category = "Vêtements",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Esprit Ruaudin",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 33,
                            Category = "Factures",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Impot",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 34,
                            Category = "Loisir",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Cultura",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 35,
                            Category = "Santé",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Harmonie",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 36,
                            Category = "Santé",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Siaci Saint Honore",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 37,
                            Category = "Neutre",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Bsa Finances*Virement*Faveur*Malinowski",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 38,
                            Category = "Transport",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Cofir*Rueil",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 39,
                            Category = "Prêt",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Realisation De Pret",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 40,
                            Category = "Prêt",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Remboursement De Pr*t",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 41,
                            Category = "Loisir",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Bk Rest",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 42,
                            Category = "Loisir",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Burger King",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 43,
                            Category = "Loisir",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Crousty",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 44,
                            Category = "Loisir",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Haochi",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 45,
                            Category = "Loisir",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Kebab",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 46,
                            Category = "Loisir",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Lgpo",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 47,
                            Category = "Loisir",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Mac Donald",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 48,
                            Category = "Loisir",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Mc Donald",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 49,
                            Category = "Loisir",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "P'tits Ponts",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 50,
                            Category = "Autre",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Retrait Au Distributeur",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 51,
                            Category = "Revenu",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Serac",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 52,
                            Category = "Revenu",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Virement Salaire",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 53,
                            Category = "Santé",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "C.P.A.M.",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 54,
                            Category = "Santé",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Phie",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 55,
                            Category = "Transport",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Setram",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 56,
                            Category = "Transport",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Sncf",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 57,
                            Category = "Travaux",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Brico Depot",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 58,
                            Category = "Travaux",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Lapeyre",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 59,
                            Category = "Travaux",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Leroy",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 60,
                            Category = "Travaux",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Ppg 72",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 61,
                            Category = "Travaux",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "point p",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 62,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "LES-BOUCHERS-REGIONAU",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 63,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "LES JARDINS VOYAGEURS SAIN",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 64,
                            Category = "Santé",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "DR VIANNAY",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 65,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Biocoop",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 66,
                            Category = "Santé",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Latrouite",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 67,
                            Category = "Loisir",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "LA CUISINE DU SO LA FERTE",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 68,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "LE FENOUIL LE MANS",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 69,
                            Category = "Santé",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "PHARMACIE",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 70,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "CLAP BOULANGERI",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 71,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "HENRIOT THOMAS",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 72,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "MAISON LEGUI LE MANS",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 73,
                            Category = "Transport",
                            Comment = "Essence",
                            IsUsed = true,
                            Pattern = "E.LECLERC LE MANS CEDEX",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 74,
                            Category = "Assurance",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "GAN ASSURANCES PLV CLT",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 75,
                            Category = "Loisir",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Deezer",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 76,
                            Category = "Santé",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "INGUERE ALICE LE MANS",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 77,
                            Category = "Factures",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "FREE MOBILE",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 78,
                            Category = "Loisir",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "UDEMY",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 79,
                            Category = "Factures",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "PRLV CEDETEL",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 80,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "PALAIS DES THES",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 81,
                            Category = "Factures",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "TotalEnergies",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 82,
                            Category = "Santé",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Psychomot",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 83,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "BELLE GARDE SAVIGNE",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 84,
                            Category = "Revenu",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "kdopapymamie",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 85,
                            Category = "Loisir",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "PN LOISIRS PARIS",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 86,
                            Category = "Loisir",
                            Comment = "Manège",
                            IsUsed = true,
                            Pattern = "CREATTITUDE",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 87,
                            Category = "Transport",
                            Comment = "Essence",
                            IsUsed = true,
                            Pattern = "RELAIS MANS RHIN LE MANS",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 88,
                            Category = "Loisir",
                            Comment = "Mondial Tissus",
                            IsUsed = true,
                            Pattern = "GMT M374",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 89,
                            Category = "Santé",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "MAMIE MESURE LE MANS",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 90,
                            Category = "Loisir",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Google Payment I Dublin",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 91,
                            Category = "Revenu",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "VIR CAF DE LA SARTHE",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 92,
                            Category = "Prêt",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Appro remboursement Pret",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 93,
                            Category = "Factures",
                            Comment = "Impôts",
                            IsUsed = true,
                            Pattern = "PRLV DIRECTION GENERALE DES FINA 2",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 94,
                            Category = "Courses",
                            Comment = "Café BOC",
                            IsUsed = true,
                            Pattern = "DECA DEVELOPPEME ST MAIXENT",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 95,
                            Category = "Santé",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "PHARMA UNIVERSIT LE MANS",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 96,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "JARDINS DE BELLE 72460",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 97,
                            Category = "Santé",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "PHARMA BEAUREGAR",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 98,
                            Category = "Transport",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "ST0072 LE MANS",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 99,
                            Category = "Loisir",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "S EVEILLER SIMPL 69290 CRAPONNE",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 100,
                            Category = "Factures",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "PRLV ECOLE SAINT PAVIN",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 101,
                            Category = "Santé",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "L'ARTISANE LE MANS",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 102,
                            Category = "Loisir",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "TIDAL Malmo",
                            UsageCount = 0
                        });
                });

            modelBuilder.Entity("BudgetTrackerApi.Models.CcImportLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("BankName")
                        .HasColumnType("TEXT")
                        .HasColumnName("bank_name");

                    b.Property<DateTime?>("DateMax")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_max");

                    b.Property<DateTime?>("DateMin")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_min");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_name");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("import_date");

                    b.Property<int>("InsertedRows")
                        .HasColumnType("INTEGER")
                        .HasColumnName("inserted_rows");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_successful");

                    b.Property<string>("MsgErreur")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("msg_erreur");

                    b.Property<double>("ProcessingTimeMs")
                        .HasColumnType("REAL")
                        .HasColumnName("processing_time_ms");

                    b.Property<int>("TotalRows")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_rows");

                    b.HasKey("Id");

                    b.ToTable("cc_import_logs");
                });

            modelBuilder.Entity("BudgetTrackerApi.Models.CcOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL")
                        .HasColumnName("amount");

                    b.Property<string>("Bank")
                        .HasColumnType("TEXT")
                        .HasColumnName("bank");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT")
                        .HasColumnName("comment");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Hash")
                        .HasColumnType("TEXT")
                        .HasColumnName("hash");

                    b.Property<int?>("ImportLogId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("import_log_id");

                    b.HasKey("Id");

                    b.HasIndex("ImportLogId");

                    b.ToTable("cc_operations", (string)null);
                });

            modelBuilder.Entity("BudgetTrackerApi.Models.LifeInsurance.LifeInsuranceAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("owner");

                    b.Property<int>("UpdateFrequencyInMonths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("update_frequency_in_months");

                    b.HasKey("Id");

                    b.ToTable("life_insurance_accounts");
                });

            modelBuilder.Entity("BudgetTrackerApi.Models.LifeInsurance.LifeInsuranceLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("IsScpi")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_scpi");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<int>("LifeInsuranceAccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("life_insurance_account_id");

                    b.HasKey("Id");

                    b.HasIndex("LifeInsuranceAccountId");

                    b.ToTable("life_insurance_lines");
                });

            modelBuilder.Entity("BudgetTrackerApi.Models.LifeInsurance.LifeInsuranceStatement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<int>("LifeInsuranceLineId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("life_insurance_line_id");

                    b.Property<decimal>("UnitCount")
                        .HasColumnType("TEXT")
                        .HasColumnName("unit_count");

                    b.Property<decimal>("UnitValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("unit_value");

                    b.HasKey("Id");

                    b.HasIndex("LifeInsuranceLineId");

                    b.ToTable("life_insurance_statements");
                });

            modelBuilder.Entity("BudgetTrackerApi.Models.PeaCachedStockPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CacheTimestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("cache_timestamp");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT")
                        .HasColumnName("price");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ticker");

                    b.HasKey("Id");

                    b.ToTable("pea_cached_stock_prices");
                });

            modelBuilder.Entity("BudgetTrackerApi.Models.PeaOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<double>("GrossUnitAmount")
                        .HasColumnType("REAL")
                        .HasColumnName("gross_unit_amount");

                    b.Property<double>("NetAmount")
                        .HasColumnType("REAL")
                        .HasColumnName("net_amount");

                    b.Property<string>("Owner")
                        .HasColumnType("TEXT")
                        .HasColumnName("owner");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantite");

                    b.HasKey("Id");

                    b.ToTable("pea_operations", (string)null);
                });

            modelBuilder.Entity("BudgetTrackerApi.Models.Savings.SavingAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("BankName")
                        .HasColumnType("TEXT")
                        .HasColumnName("bank_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("owner");

                    b.Property<int>("UpdateFrequencyInMonths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("update_frequency_in_months");

                    b.HasKey("Id");

                    b.ToTable("saving_accounts");
                });

            modelBuilder.Entity("BudgetTrackerApi.Models.Savings.SavingStatement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<int>("SavingAccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("saving_account_id");

                    b.HasKey("Id");

                    b.HasIndex("SavingAccountId");

                    b.ToTable("saving_statements");
                });

            modelBuilder.Entity("BudgetTrackerApi.Models.CcOperation", b =>
                {
                    b.HasOne("BudgetTrackerApi.Models.CcImportLog", "ImportLog")
                        .WithMany("Operations")
                        .HasForeignKey("ImportLogId");

                    b.Navigation("ImportLog");
                });

            modelBuilder.Entity("BudgetTrackerApi.Models.LifeInsurance.LifeInsuranceLine", b =>
                {
                    b.HasOne("BudgetTrackerApi.Models.LifeInsurance.LifeInsuranceAccount", "Account")
                        .WithMany("Lines")
                        .HasForeignKey("LifeInsuranceAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BudgetTrackerApi.Models.LifeInsurance.LifeInsuranceStatement", b =>
                {
                    b.HasOne("BudgetTrackerApi.Models.LifeInsurance.LifeInsuranceLine", "Line")
                        .WithMany("Statements")
                        .HasForeignKey("LifeInsuranceLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Line");
                });

            modelBuilder.Entity("BudgetTrackerApi.Models.Savings.SavingStatement", b =>
                {
                    b.HasOne("BudgetTrackerApi.Models.Savings.SavingAccount", "Account")
                        .WithMany("Statements")
                        .HasForeignKey("SavingAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BudgetTrackerApi.Models.CcImportLog", b =>
                {
                    b.Navigation("Operations");
                });

            modelBuilder.Entity("BudgetTrackerApi.Models.LifeInsurance.LifeInsuranceAccount", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("BudgetTrackerApi.Models.LifeInsurance.LifeInsuranceLine", b =>
                {
                    b.Navigation("Statements");
                });

            modelBuilder.Entity("BudgetTrackerApi.Models.Savings.SavingAccount", b =>
                {
                    b.Navigation("Statements");
                });
#pragma warning restore 612, 618
        }
    }
}
