// <auto-generated />
using System;
using BudgetTrackerApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BudgetTrackerApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260210212511_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("BudgetTrackerApi.Data.CcCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("MacroCategory")
                        .HasColumnType("TEXT")
                        .HasColumnName("macro_category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("cc_categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MacroCategory = "Obligatoire",
                            Name = "Prêt"
                        },
                        new
                        {
                            Id = 2,
                            MacroCategory = "Obligatoire",
                            Name = "Courses"
                        },
                        new
                        {
                            Id = 3,
                            MacroCategory = "Obligatoire",
                            Name = "Travaux"
                        },
                        new
                        {
                            Id = 4,
                            MacroCategory = "Loisir",
                            Name = "Loisir"
                        },
                        new
                        {
                            Id = 5,
                            MacroCategory = "Loisir",
                            Name = "Vacances"
                        },
                        new
                        {
                            Id = 6,
                            MacroCategory = "Obligatoire",
                            Name = "Transport"
                        },
                        new
                        {
                            Id = 7,
                            MacroCategory = "Obligatoire",
                            Name = "Factures"
                        },
                        new
                        {
                            Id = 8,
                            MacroCategory = "Obligatoire",
                            Name = "Vêtements"
                        },
                        new
                        {
                            Id = 9,
                            MacroCategory = "Loisir",
                            Name = "Cadeaux"
                        },
                        new
                        {
                            Id = 10,
                            MacroCategory = "Obligatoire",
                            Name = "Santé"
                        },
                        new
                        {
                            Id = 11,
                            MacroCategory = "Obligatoire",
                            Name = "Autres"
                        },
                        new
                        {
                            Id = 12,
                            MacroCategory = "Obligatoire",
                            Name = "Maison/Equip."
                        },
                        new
                        {
                            Id = 13,
                            MacroCategory = "Neutre",
                            Name = "Neutre"
                        },
                        new
                        {
                            Id = 14,
                            MacroCategory = "Revenu",
                            Name = "Revenu"
                        });
                });

            modelBuilder.Entity("BudgetTrackerApi.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("BankName")
                        .HasColumnType("TEXT")
                        .HasColumnName("bank_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("owner");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type");

                    b.Property<int>("UpdateFrequencyInMonths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("update_frequency_in_months");

                    b.HasKey("Id");

                    b.ToTable("accounts");
                });

            modelBuilder.Entity("BudgetTrackerApi.Models.CcCategoryRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT")
                        .HasColumnName("comment");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_used");

                    b.Property<DateTime?>("LastAppliedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_applied_at");

                    b.Property<double?>("MaxAmount")
                        .HasColumnType("REAL")
                        .HasColumnName("max_amount");

                    b.Property<DateTime?>("MaxDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("max_date");

                    b.Property<double?>("MinAmount")
                        .HasColumnType("REAL")
                        .HasColumnName("min_amount");

                    b.Property<DateTime?>("MinDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("min_date");

                    b.Property<string>("Pattern")
                        .HasColumnType("TEXT")
                        .HasColumnName("pattern");

                    b.Property<int>("UsageCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usage_count");

                    b.HasKey("Id");

                    b.ToTable("cc_category_rules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Santé",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "VIR GENERATION",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 2,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "MAISON LEGUI",
                            UsageCount = 0
                        });
                });

            modelBuilder.Entity("BudgetTrackerApi.Models.CcImportLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("BankName")
                        .HasColumnType("TEXT")
                        .HasColumnName("bank_name");

                    b.Property<DateTime?>("DateMax")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_max");

                    b.Property<DateTime?>("DateMin")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_min");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_name");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("import_date");

                    b.Property<int>("InsertedRows")
                        .HasColumnType("INTEGER")
                        .HasColumnName("inserted_rows");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_successful");

                    b.Property<string>("MsgErreur")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("msg_erreur");

                    b.Property<double>("ProcessingTimeMs")
                        .HasColumnType("REAL")
                        .HasColumnName("processing_time_ms");

                    b.Property<int>("TotalRows")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_rows");

                    b.HasKey("Id");

                    b.ToTable("cc_import_logs");
                });

            modelBuilder.Entity("BudgetTrackerApi.Models.CcOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL")
                        .HasColumnName("amount");

                    b.Property<string>("Bank")
                        .HasColumnType("TEXT")
                        .HasColumnName("bank");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT")
                        .HasColumnName("comment");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Hash")
                        .HasColumnType("TEXT")
                        .HasColumnName("hash");

                    b.Property<int?>("ImportLogId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("import_log_id");

                    b.HasKey("Id");

                    b.HasIndex("ImportLogId");

                    b.ToTable("cc_operations", (string)null);
                });

            modelBuilder.Entity("BudgetTrackerApi.Models.LifeInsurance.LifeInsuranceLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("account_id");

                    b.Property<bool>("IsScpi")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_scpi");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("life_insurance_lines");
                });

            modelBuilder.Entity("BudgetTrackerApi.Models.LifeInsurance.LifeInsuranceStatement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<int>("LifeInsuranceLineId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("life_insurance_line_id");

                    b.Property<decimal>("UnitCount")
                        .HasColumnType("TEXT")
                        .HasColumnName("unit_count");

                    b.Property<decimal>("UnitValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("unit_value");

                    b.HasKey("Id");

                    b.HasIndex("LifeInsuranceLineId");

                    b.ToTable("life_insurance_statements");
                });

            modelBuilder.Entity("BudgetTrackerApi.Models.PeaCachedStockPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CacheTimestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("cache_timestamp");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT")
                        .HasColumnName("price");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ticker");

                    b.HasKey("Id");

                    b.ToTable("pea_cached_stock_prices");
                });

            modelBuilder.Entity("BudgetTrackerApi.Models.PeaOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<double>("GrossUnitAmount")
                        .HasColumnType("REAL")
                        .HasColumnName("gross_unit_amount");

                    b.Property<double>("NetAmount")
                        .HasColumnType("REAL")
                        .HasColumnName("net_amount");

                    b.Property<string>("Owner")
                        .HasColumnType("TEXT")
                        .HasColumnName("owner");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantite");

                    b.HasKey("Id");

                    b.ToTable("pea_operations", (string)null);
                });

            modelBuilder.Entity("BudgetTrackerApi.Models.Savings.SavingStatement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("saving_statements");
                });

            modelBuilder.Entity("BudgetTrackerApi.Models.CcOperation", b =>
                {
                    b.HasOne("BudgetTrackerApi.Models.CcImportLog", "ImportLog")
                        .WithMany("Operations")
                        .HasForeignKey("ImportLogId");

                    b.Navigation("ImportLog");
                });

            modelBuilder.Entity("BudgetTrackerApi.Models.LifeInsurance.LifeInsuranceLine", b =>
                {
                    b.HasOne("BudgetTrackerApi.Models.Account", "Account")
                        .WithMany("LifeInsuranceLines")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BudgetTrackerApi.Models.LifeInsurance.LifeInsuranceStatement", b =>
                {
                    b.HasOne("BudgetTrackerApi.Models.LifeInsurance.LifeInsuranceLine", "Line")
                        .WithMany("Statements")
                        .HasForeignKey("LifeInsuranceLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Line");
                });

            modelBuilder.Entity("BudgetTrackerApi.Models.Savings.SavingStatement", b =>
                {
                    b.HasOne("BudgetTrackerApi.Models.Account", "Account")
                        .WithMany("SavingStatements")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BudgetTrackerApi.Models.Account", b =>
                {
                    b.Navigation("LifeInsuranceLines");

                    b.Navigation("SavingStatements");
                });

            modelBuilder.Entity("BudgetTrackerApi.Models.CcImportLog", b =>
                {
                    b.Navigation("Operations");
                });

            modelBuilder.Entity("BudgetTrackerApi.Models.LifeInsurance.LifeInsuranceLine", b =>
                {
                    b.Navigation("Statements");
                });
#pragma warning restore 612, 618
        }
    }
}
