// <auto-generated />
using System;
using BudgetTrackerApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BudgetTrackerApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260103190037_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("BudgetTrackerApp.Data.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("BudgetTrackerApp.Models.CachedStockPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CacheTimestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("cache_timestamp");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT")
                        .HasColumnName("price");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ticker");

                    b.HasKey("Id");

                    b.ToTable("cached_stock_prices");
                });

            modelBuilder.Entity("BudgetTrackerApp.Models.CategoryRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("Commentaire")
                        .HasColumnType("TEXT")
                        .HasColumnName("commentaire");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_used");

                    b.Property<double?>("MaxAmount")
                        .HasColumnType("REAL")
                        .HasColumnName("max_amount");

                    b.Property<DateTime?>("MaxDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("max_date");

                    b.Property<double?>("MinAmount")
                        .HasColumnType("REAL")
                        .HasColumnName("min_amount");

                    b.Property<DateTime?>("MinDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("min_date");

                    b.Property<string>("Pattern")
                        .HasColumnType("TEXT")
                        .HasColumnName("pattern");

                    b.HasKey("Id");

                    b.ToTable("category_rules", (string)null);
                });

            modelBuilder.Entity("BudgetTrackerApp.Models.OperationCC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Banque")
                        .HasColumnType("TEXT")
                        .HasColumnName("banque");

                    b.Property<string>("Categorie")
                        .HasColumnType("TEXT")
                        .HasColumnName("categorie");

                    b.Property<string>("Commentaire")
                        .HasColumnType("TEXT")
                        .HasColumnName("commentaire");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("DateImport")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_import");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Hash")
                        .HasColumnType("TEXT")
                        .HasColumnName("hash");

                    b.Property<double>("Montant")
                        .HasColumnType("REAL")
                        .HasColumnName("montant");

                    b.HasKey("Id");

                    b.ToTable("operations_cc", (string)null);
                });

            modelBuilder.Entity("BudgetTrackerApp.Models.OperationPea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<double>("MontantBrutUnitaire")
                        .HasColumnType("REAL")
                        .HasColumnName("montant_brut_unitaire");

                    b.Property<double>("MontantNet")
                        .HasColumnType("REAL")
                        .HasColumnName("montant_net");

                    b.Property<int>("Quantité")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantite")
                        .HasAnnotation("Relational:JsonPropertyName", "quantite");

                    b.Property<string>("Titulaire")
                        .HasColumnType("TEXT")
                        .HasColumnName("titulaire");

                    b.HasKey("Id");

                    b.ToTable("operations_pea", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
