// <auto-generated />
using System;
using BudgetTrackerApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BudgetTrackerApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("BudgetTrackerApi.Data.CcCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("cc_categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Prêt",
                            Type = "Obligatoire"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Courses",
                            Type = "Obligatoire"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Travaux",
                            Type = "Obligatoire"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Loisir",
                            Type = "Loisir"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Vacances",
                            Type = "Loisir"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Transport",
                            Type = "Obligatoire"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Factures",
                            Type = "Obligatoire"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Vêtements",
                            Type = "Obligatoire"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Cadeaux",
                            Type = "Loisir"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Santé",
                            Type = "Obligatoire"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Autres",
                            Type = "Obligatoire"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Maison/Equip.",
                            Type = "Obligatoire"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Neutre",
                            Type = "Neutre"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Revenu",
                            Type = "Revenu"
                        });
                });

            modelBuilder.Entity("BudgetTrackerApi.Models.CcCategoryRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT")
                        .HasColumnName("comment");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_used");

                    b.Property<double?>("MaxAmount")
                        .HasColumnType("REAL")
                        .HasColumnName("max_amount");

                    b.Property<DateTime?>("MaxDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("max_date");

                    b.Property<double?>("MinAmount")
                        .HasColumnType("REAL")
                        .HasColumnName("min_amount");

                    b.Property<DateTime?>("MinDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("min_date");

                    b.Property<string>("Pattern")
                        .HasColumnType("TEXT")
                        .HasColumnName("pattern");

                    b.HasKey("Id");

                    b.ToTable("cc_category_rules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Santé",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "VIR GENERATION"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "MAISON LEGUI"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Travaux",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Castorama"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Factures",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Sfr"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Ammeublement",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "edm"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Prêt",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Assu. Cnp Pret Habitat"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Santé",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Bio's Hair"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Auchan Le Mans"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Boulangerie"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Carrefour City Le Mans"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Factures",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "PRLV DIRECTION GENERALE DES FINA"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Carrefour Lemans"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Casino Shop"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Eleveurs Regionaux"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Fournil D'edison"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Grand*Frais"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Leclerc*Web"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Lidl"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Mgp*la Ruche"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Mie*Caline"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "U Express"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Factures",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Direct*Energie"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Factures",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "ENI Gas"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Factures",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Tres.  Le Mans Ville"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Transport",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Auchan Carburant"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Transport",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Dac Intermarche"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Transport",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "E.Leclerc Laval Cedex"
                        },
                        new
                        {
                            Id = 28,
                            Category = "Transport",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Relais*Le*Mans*R"
                        },
                        new
                        {
                            Id = 29,
                            Category = "Transport",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Stat Leclerc 24/24"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Transport",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Station U 72"
                        },
                        new
                        {
                            Id = 31,
                            Category = "Factures",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Cabriole"
                        },
                        new
                        {
                            Id = 32,
                            Category = "Vêtements",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Esprit Ruaudin"
                        },
                        new
                        {
                            Id = 33,
                            Category = "Factures",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Impot"
                        },
                        new
                        {
                            Id = 34,
                            Category = "Loisir",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Cultura"
                        },
                        new
                        {
                            Id = 35,
                            Category = "Santé",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Harmonie"
                        },
                        new
                        {
                            Id = 36,
                            Category = "Santé",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Siaci Saint Honore"
                        },
                        new
                        {
                            Id = 37,
                            Category = "Neutre",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Bsa Finances*Virement*Faveur*Malinowski"
                        },
                        new
                        {
                            Id = 38,
                            Category = "Transport",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Cofir*Rueil"
                        },
                        new
                        {
                            Id = 39,
                            Category = "Prêt",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Realisation De Pret"
                        },
                        new
                        {
                            Id = 40,
                            Category = "Prêt",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Remboursement De Pr*t"
                        },
                        new
                        {
                            Id = 41,
                            Category = "Loisir",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Bk Rest"
                        },
                        new
                        {
                            Id = 42,
                            Category = "Loisir",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Burger King"
                        },
                        new
                        {
                            Id = 43,
                            Category = "Loisir",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Crousty"
                        },
                        new
                        {
                            Id = 44,
                            Category = "Loisir",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Haochi"
                        },
                        new
                        {
                            Id = 45,
                            Category = "Loisir",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Kebab"
                        },
                        new
                        {
                            Id = 46,
                            Category = "Loisir",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Lgpo"
                        },
                        new
                        {
                            Id = 47,
                            Category = "Loisir",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Mac Donald"
                        },
                        new
                        {
                            Id = 48,
                            Category = "Loisir",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Mc Donald"
                        },
                        new
                        {
                            Id = 49,
                            Category = "Loisir",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "P'tits Ponts"
                        },
                        new
                        {
                            Id = 50,
                            Category = "Autre",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Retrait Au Distributeur"
                        },
                        new
                        {
                            Id = 51,
                            Category = "Revenu",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Serac"
                        },
                        new
                        {
                            Id = 52,
                            Category = "Revenu",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Virement Salaire"
                        },
                        new
                        {
                            Id = 53,
                            Category = "Santé",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "C.P.A.M."
                        },
                        new
                        {
                            Id = 54,
                            Category = "Santé",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Phie"
                        },
                        new
                        {
                            Id = 55,
                            Category = "Transport",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Setram"
                        },
                        new
                        {
                            Id = 56,
                            Category = "Transport",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Sncf"
                        },
                        new
                        {
                            Id = 57,
                            Category = "Travaux",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Brico Depot"
                        },
                        new
                        {
                            Id = 58,
                            Category = "Travaux",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Lapeyre"
                        },
                        new
                        {
                            Id = 59,
                            Category = "Travaux",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Leroy"
                        },
                        new
                        {
                            Id = 60,
                            Category = "Travaux",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Ppg 72"
                        },
                        new
                        {
                            Id = 61,
                            Category = "Travaux",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "point p"
                        },
                        new
                        {
                            Id = 62,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "LES-BOUCHERS-REGIONAU"
                        },
                        new
                        {
                            Id = 63,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "LES JARDINS VOYAGEURS SAIN"
                        },
                        new
                        {
                            Id = 64,
                            Category = "Santé",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "DR VIANNAY"
                        },
                        new
                        {
                            Id = 65,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Biocoop"
                        },
                        new
                        {
                            Id = 66,
                            Category = "Santé",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Latrouite"
                        },
                        new
                        {
                            Id = 67,
                            Category = "Loisir",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "LA CUISINE DU SO LA FERTE"
                        },
                        new
                        {
                            Id = 68,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "LE FENOUIL LE MANS"
                        },
                        new
                        {
                            Id = 69,
                            Category = "Santé",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "PHARMACIE"
                        },
                        new
                        {
                            Id = 70,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "CLAP BOULANGERI"
                        },
                        new
                        {
                            Id = 71,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "HENRIOT THOMAS"
                        },
                        new
                        {
                            Id = 72,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "MAISON LEGUI LE MANS"
                        },
                        new
                        {
                            Id = 73,
                            Category = "Transport",
                            Comment = "Essence",
                            IsUsed = true,
                            Pattern = "E.LECLERC LE MANS CEDEX"
                        },
                        new
                        {
                            Id = 74,
                            Category = "Assurance",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "GAN ASSURANCES PLV CLT"
                        },
                        new
                        {
                            Id = 75,
                            Category = "Loisir",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Deezer"
                        },
                        new
                        {
                            Id = 76,
                            Category = "Santé",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "INGUERE ALICE LE MANS"
                        },
                        new
                        {
                            Id = 77,
                            Category = "Factures",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "FREE MOBILE"
                        },
                        new
                        {
                            Id = 78,
                            Category = "Loisir",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "UDEMY"
                        },
                        new
                        {
                            Id = 79,
                            Category = "Factures",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "PRLV CEDETEL"
                        },
                        new
                        {
                            Id = 80,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "PALAIS DES THES"
                        },
                        new
                        {
                            Id = 81,
                            Category = "Factures",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "TotalEnergies"
                        },
                        new
                        {
                            Id = 82,
                            Category = "Santé",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Psychomot"
                        },
                        new
                        {
                            Id = 83,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "BELLE GARDE SAVIGNE"
                        },
                        new
                        {
                            Id = 84,
                            Category = "Revenu",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "kdopapymamie"
                        },
                        new
                        {
                            Id = 85,
                            Category = "Loisir",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "PN LOISIRS PARIS"
                        },
                        new
                        {
                            Id = 86,
                            Category = "Loisir",
                            Comment = "Manège",
                            IsUsed = true,
                            Pattern = "CREATTITUDE"
                        },
                        new
                        {
                            Id = 87,
                            Category = "Transport",
                            Comment = "Essence",
                            IsUsed = true,
                            Pattern = "RELAIS MANS RHIN LE MANS"
                        },
                        new
                        {
                            Id = 88,
                            Category = "Loisir",
                            Comment = "Mondial Tissus",
                            IsUsed = true,
                            Pattern = "GMT M374"
                        },
                        new
                        {
                            Id = 89,
                            Category = "Santé",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "MAMIE MESURE LE MANS"
                        },
                        new
                        {
                            Id = 90,
                            Category = "Loisir",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Google Payment I Dublin"
                        },
                        new
                        {
                            Id = 91,
                            Category = "Revenu",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "VIR CAF DE LA SARTHE"
                        },
                        new
                        {
                            Id = 92,
                            Category = "Prêt",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "Appro remboursement Pret"
                        },
                        new
                        {
                            Id = 93,
                            Category = "Factures",
                            Comment = "Impôts",
                            IsUsed = true,
                            Pattern = "PRLV DIRECTION GENERALE DES FINA 2"
                        },
                        new
                        {
                            Id = 94,
                            Category = "Courses",
                            Comment = "Café BOC",
                            IsUsed = true,
                            Pattern = "DECA DEVELOPPEME ST MAIXENT"
                        },
                        new
                        {
                            Id = 95,
                            Category = "Santé",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "PHARMA UNIVERSIT LE MANS"
                        },
                        new
                        {
                            Id = 96,
                            Category = "Courses",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "JARDINS DE BELLE 72460"
                        },
                        new
                        {
                            Id = 97,
                            Category = "Santé",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "PHARMA BEAUREGAR"
                        },
                        new
                        {
                            Id = 98,
                            Category = "Transport",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "ST0072 LE MANS"
                        },
                        new
                        {
                            Id = 99,
                            Category = "Loisir",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "S EVEILLER SIMPL 69290 CRAPONNE"
                        },
                        new
                        {
                            Id = 100,
                            Category = "Factures",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "PRLV ECOLE SAINT PAVIN"
                        },
                        new
                        {
                            Id = 101,
                            Category = "Santé",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "L'ARTISANE LE MANS"
                        },
                        new
                        {
                            Id = 102,
                            Category = "Loisir",
                            Comment = "",
                            IsUsed = true,
                            Pattern = "TIDAL Malmo"
                        });
                });

            modelBuilder.Entity("BudgetTrackerApi.Models.CcOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Banque")
                        .HasColumnType("TEXT")
                        .HasColumnName("banque");

                    b.Property<string>("Categorie")
                        .HasColumnType("TEXT")
                        .HasColumnName("categorie");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT")
                        .HasColumnName("comment");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("DateImport")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_import");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Hash")
                        .HasColumnType("TEXT")
                        .HasColumnName("hash");

                    b.Property<double>("Montant")
                        .HasColumnType("REAL")
                        .HasColumnName("montant");

                    b.HasKey("Id");

                    b.ToTable("cc_operations", (string)null);
                });

            modelBuilder.Entity("BudgetTrackerApi.Models.PeaCachedStockPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CacheTimestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("cache_timestamp");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT")
                        .HasColumnName("price");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ticker");

                    b.HasKey("Id");

                    b.ToTable("pea_cached_stock_prices");
                });

            modelBuilder.Entity("BudgetTrackerApi.Models.PeaOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<double>("MontantBrutUnitaire")
                        .HasColumnType("REAL")
                        .HasColumnName("montant_brut_unitaire");

                    b.Property<double>("MontantNet")
                        .HasColumnType("REAL")
                        .HasColumnName("montant_net");

                    b.Property<int>("Quantité")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantite")
                        .HasAnnotation("Relational:JsonPropertyName", "quantite");

                    b.Property<string>("Titulaire")
                        .HasColumnType("TEXT")
                        .HasColumnName("titulaire");

                    b.HasKey("Id");

                    b.ToTable("pea_operations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
